### ISSUE TITLE
Facilitators do 2 daily checkins instead of 1

### ISSUE THREAD

**Issue by andrewedstrom** [pivotal/cf-onboarding#108]
This was suggested in the retro for the February onboarding week. Participants felt like they would benefit from having an additional opportunity to ask questions

**Comment by dsabeti** [comment]
There's a [facilitation guide](https://github.com/pivotal-cf/onboarding/blob/master/FACILITATING.md), but we're worried it'll get too long. Let's set up a facilitation guide will multiple pages in the Wiki. We can make sure to include about this there.

**Comment by dprotaso** [comment]
From my experience (acting as a facilitator) I've found it good practice to let the onboarding participants know that I can be interrupted throughout the week at any time.

Secondly, if I know the problem can be answered by a team (even though I may know the solution) I will always delegate so that people learn to approach teams for help. It's also a benefit to meet the team in person (If possible)

**Comment by dsabeti** [comment]
Done.
