### ISSUE TITLE
Shiftit for workstation setup?

### ISSUE THREAD

**Issue by andrewgilbert12** [pivotal/cf-onboarding#139]
It's nice to have, and we're used to having it on our desktops

**Comment by dsabeti** [comment]
Here's where we keep our scripts for installing everything: https://github.com/pivotal-cf-experimental/onboarding-week-construct

**Comment by sjolicoeur** [comment]
maybe we could use: https://github.com/jgamblin/MacOS-Config

**Comment by dsabeti** [comment]
@sjolicoeur. I'd be open to a tool besides construct, but I'm also not aware of any specific problems with it. Was there something you thought this other tool could do better than construct?

And to make sure we don't lose the original thread here: the ask of this issue is to add ShiftIt to our onboarding machines. Neither the Construct nor this other tool (MacOS-Config) include it currently. I think it would probably be simpler to add ShiftIt to Construct, but I'm open to other tools if you think it would make it easier to add, or to maintain in the long run.

**Comment by ljfranklin** [comment]
Added ShiftIt here: https://github.com/pivotal-cf-experimental/onboarding-week-construct/commit/28d0daf5c50778fa8d308ce157252ebd8ae2753b. Thanks for the suggestion, closing this out.
