### ISSUE TITLE
bbl up command has unsupported flags

### ISSUE THREAD

**Issue by andrewgilbert12** [pivotal/cf-onboarding#140]
in the bbl up story, the command `bbl up --gcp-zone us-east1-b --gcp-region us-east1 --gcp-service-account-key service-account.key.json --iaas gcp --gcp-project-id PROJECT_ID` has the flags `--gcp-zone` and `--gcp-project-id` which aren't supported by the most recent version of bbl.

**Comment by andrewgilbert12** [comment]
Also, for the story https://www.pivotaltracker.com/story/show/159048397 the `bbl create-lbs` command is deprecated, it looks like we need to specify the load balancer info in the `bbl up` command with the `--lb-type`, etc. flags. We re-ran `bbl up` adding the load balancer flags and it finished within 15 seconds.

**Comment by dsabeti** [comment]
Hey @andrewgilbert12. I wonder if you ended up with an older version of the stories. The `master` branch of the repo [doesn't include the deprecated flags](https://github.com/pivotal-cf/onboarding/blob/master/deploy_oss.prolific#L174-L177). Similarly, the instructions for creating the load balancer [use `bbl plan` instead of `bbl create-lbs`](https://github.com/pivotal-cf/onboarding/blob/master/deploy_oss.prolific#L341-L345).

**Comment by dsabeti** [comment]
Ok, we figured out what happened. Different facilitators have been using different versions of the stories. We're hoping that addressing [this issue](https://github.com/pivotal-cf/onboarding/issues/142) (https://github.com/pivotal-cf/onboarding/issues/142) will prevent this in the future.
