### ISSUE TITLE
Can the onboarding construct be changed so that we don't have to provide the password a dozen times?

### ISSUE THREAD

**Issue by dsabeti** [pivotal/cf-onboarding#143]

**Comment by ljfranklin** [comment]
Turns out the `construct` script allows you to specify "priority" scripts which will run first. So I moved all the script which need root and prompt for your password to run first: https://github.com/pivotal-cf-experimental/onboarding-week-construct/commit/7eae359c9867564b4496fcac4ab19963a6bc0068. So it still prompts your a couple times for your password, but it's all within the first 5 minutes of running the script.

You could do a more robust solution where you run `sudo ./construct` and the script does `su -u $SUDO_USER` if a script doesn't need root, but that sounds like more trouble than it's worth. Closing this out.
