### ISSUE TITLE
Consider pivotal workstation-setup for base image

### ISSUE THREAD

**Issue by professor** [pivotal/cf-onboarding#189]
https://github.com/pivotal/workstation-setup/ just has many of the tools that I expect on a Pivotal workstation.

**Comment by ljfranklin** [comment]
@professor what tools specifically were missing from the current setup? Since we re-image the machines before each week, we want the install script to finish as quickly as possible. I suspect the `workstation-setup` repo includes a bunch of stuff that isn't necessary for onboarding week and would increase the time to install.

**Comment by bwinter** [comment]
Currently we are using a version of the `construct` workstation setup tooling and it would be easy to add some additional tools.

To help keep the on-boarding facilitators' life simpler it would be nice to close this if we don't get suggestions.

**Comment by bwinter** [comment]
Going to close this since we haven't heard back in a bit. Feel free to re-open if the issue arrises again. 👍
