### ISSUE TITLE
Create an OPS file story

### ISSUE THREAD

**Issue by astrieanna** [pivotal/cf-onboarding#29]
Both bbl and bosh accept ops files. Add a story that involves creating an ops-file (rather than just passing one in).

**Comment by keaty** [comment]
**Note:** A good ops file story would be to add a user that allows the participant to ssh into the bosh director. Once you're in the bosh director, you can edit cool stuff like whether the director cleans up compilation VMs (useful if compilations are inexplicably failing). A story like this would incorporate the use of the bbl `./create-env` script.

**Comment by dsabeti** [comment]
[This commit (6e67f065)](https://github.com/pivotal-cf/onboarding/commit/6e67f06516faedea153ca16ef2693a0844ddbb37) adds instructions for writing an ops-file to scale up the diego cells. This covers the BOSH case but not the bbl case. I'm going to close the issue for now, since we have some coverage, but I do think it's worth noting that we're thinking about making an "advanced operator" module, which could definitely include writing ops-files for `bbl`.
