### ISSUE TITLE
EPIC: opsman and ERT

### ISSUE THREAD

**Issue by zankich** [pivotal/cf-onboarding#37]
Most of the epics and stories in this backlog are focused on the open source cloud foundry and bosh, however many teams work on PCF and PCF tiles. It would awesome if there was an epic which went through the opsman and ERT lifecycle.

In addition to this, it would be great to also install a service tile and go through the interaction between PCF and a service.

cc @kkallday

**Comment by kkallday** [comment]
Sound good! I'll get started this week.

**Comment by keaty** [comment]
Thanks for writing this issue up @zankich!

@kkallday, it would be so amazing if you tackled this. One thought I had re: PCF stories was that they might be able to take advantage of the Toolsmiths env generating pipelines etc. It depends on how much time you want participants to focus on setup vs use.

**Comment by kkallday** [comment]
@keaty I was thinking that the participants would use our terraform templates (https://github.com/pivotal-cf/terraforming-gcp) to stand up the required infrastructure and an Opsman then use `om` (https://github.com/pivotal-cf/om) to upload/configure/deploy tiles, namely the ERT. This would ideally come after an epic that covers deploying OSS Cloud Foundry via cf-deployment.

It would be similar to this blog post: http://engineering.pivotal.io/post/release-engineering-deploying-ert/.

Let me know if this sounds a like a decent plan. I can take a stab at it and we can review together (and/or @zankich).

**Comment by keaty** [comment]
@kkallday this may be an ignorant question, but is there a way to Terraform deploy Opsman etc. for use with a pre-existing OSS CF? I'd like to keep the amount of time spent waiting for things to run to a minimum, and since participants will have already deployed an OSS CF it would be great if they could use it to expedite the process and explore the diff between the CF & PCF. (Not to mention, entirely deploying (P)CF twice will increase the cost of running one of these weeks by a bit.)

**Comment by kkallday** [comment]
@keaty that is a great point. The infrastructure (load balancer, VPC, firewall rules, etc) that is deployed for OSS CF can be reused for deploying the ERT. However, there isn't a good way of "importing" an OSS CF into Opsman so that it can add the proprietary components (autoscaling, apps manager, etc). Any ideas that come to mind are hacky and wouldn't be a good experience given this is for onboarding. Furthermore, ERT takes approximately 2.5 hours to deploy.

There are many similarities between deploying OSS CF and PCF. Maybe the goal of this epic should be to learn about PCF and the services that are typically deployed alongside it. For instance, we can show how an application developer would use a service like MySQL or Redis. If we go this route PCF Dev would be a good option. It runs locally, short time to setup, and it has  Redis, RabbitMQ, MySQL, and Spring Cloud Services built in (which would normally be tiles deployed alongside).

**Comment by keaty** [comment]
@kkallday more service stories would be great—as it stands I've only created a set for Redis CUPS.

But to learn about the operator experience with tiles etc...it might be worth a whole set of deploy stories in a third track. If you look in this repo you'll see there's a module called deploy_gcp and another called deploy_local. How about we rename deploy_gcp --> deploy_oss and then make a third set of stories called deploy_pcf. Those stories could start an entire third track of work focused on the proprietary products.

**Edit:** I've taken care of this rename to make room for a PCF module or track

**Comment by ljfranklin** [comment]
We've now got a couple small OpsMgr stories and we're adding more in this branch: https://github.com/pivotal/cf-onboarding/tree/opsman-pas. Hopefully should get this merged in the next week or so

**Comment by ljfranklin** [comment]
Closing this out as we now have a handful on PAS and Ops Manager stories in backlog.
