### ISSUE TITLE
Have a pre-existing Concourse environment

### ISSUE THREAD

**Issue by sjolicoeur** [pivotal/cf-onboarding#44]
Have a ready to go Concourse env so one could have a track that is dedicated to only setting up pipelines and not the concourse env.

**Comment by keaty** [comment]
Hi @sjolicoeur, this is a helpful suggestion! It sounds like you were doing the OSS Track. There's a separate Local Track in which participants bring Concourse up with Vagrant. Would this sort of quick deploy fulfill your request of having a Concourse env ready to go? If so, I could reword the Deploy Concourse story in the OSS Track to point out that either option is okay.

**Comment by sjolicoeur** [comment]
Or show how to deploy concourse as just another server aka "job" if possible? the concourse epic left our PCF install slightly un-usable. we rescued it by using it for a Kubo release.

**Comment by keaty** [comment]
I have a story I've been working on to manually add a Concourse load balancer so that the cf bbl lb doesn't need to be torn down. I think it'll be worthwhile for people to learn a little more about setting the full concourse deployment up. If that story ends up being too confusing for users, then I'll switch to just having people deploy a single job :)
