### ISSUE TITLE
Epic: implement a basic Concourse resource

### ISSUE THREAD

**Issue by keaty** [pivotal/cf-onboarding#5]

**Comment by astrieanna** [comment]
## Given: A fun or useful versioned software thing. (e.g. most webcomics)
## Then: Construct a Concourse Resource [Type]
*Reference: https://concourse.ci/implementing-resources.html*
1) Write check/in/out scripts that make sense for your resource
 Debugging note: write errors to stderr because stdout **MUST** only be a json object.
2) Package in a Docker container and publish to the docker registry.
3) Configure your pipeline to include your new resource type, create an instance of that resource type, and consume that resource.
4) Lots of debugging, with poor feedback mechanisms.

## Expected Result: A green pipeline again

**Comment by keaty** [comment]
Hey @astrieanna I've added a minimalist Concourse resource story, including your suggestions, in 94adf33 Thanks for the help!
