### ISSUE TITLE
Provide clearer instructions on how to get BOSH Director IP Address

### ISSUE THREAD

**Issue by shubhaat** [pivotal/cf-onboarding#83]
For this [onboarding story](https://www.pivotaltracker.com/story/show/152585778), it would have helped to know how to find the BOSH Director's IP address. We found one easy solution was to use the command `bbl director-address`, but there might be some value in not making the solution **too easy**. An intermediate solution would be to suggest using the command `bbl` to see the list of bbl commands, which includes director-address.

**Comment by dsabeti** [comment]
Hi @shubhaat. It looks like the story got updated when we upgraded to `bbl` 6, which pretty much requires operators to use `bbl print-env` to connect to their BOSH director. You can see the complete change here: https://github.com/pivotal-cf/onboarding/commit/9ea65eae

I'm going to close the issue since the story is in better shape, but I don't want to keep thinking about how we can orient more stories towards discovery and exploration, rather than merely providing answers.
